spring:
  datasource:
    username: kwicweb
    password: kwicweb
    url: jdbc:mysql://gourmet.cb8bfd82aykb.ap-northeast-2.rds.amazonaws.com:3306/gourmet
    driver-class-name: com.mysql.cj.jdbc.Driver