server:
  port: 8090

spring:
  config:
    import:
      - classpath:application-prodmysql.yml
      - classpath:application-mail.yml
    activate:
      on-profile: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      database: mysql

security:
  jwt:
    secret-key: NTRsc1JIZnVQWnVxTklJMWlzVDljdXNtc3lETE5LWGRHSGJvbGs4Rnp4QnR1OEliQW5iN1JuV2VSdVFIZDF2aw==
    access-expiration-time: 7200000
    refresh-expiration-time: 1209600000