mail:
  smtp:
    auth: true
    start-tls:
      required: true
      enable: true
    socket-factory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

  #admin 구글 계정
  admin:
    id: kwicweb13@gmail.com
    password: pplvubvwiteoczwu
